version: '3.8'

services:
  db:
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_HOST=fastapi-postgres-docker_db_1 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - fastapi-postgres
    
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
    depends_on:
      - db
    restart: always
    networks:
      - fastapi-postgres

  
volumes:
  db:
    driver: local


networks:
  fastapi-postgres:
    external: true